#!/bin/sh

set -e

function usage {
    printf "\n%s - test S-Expression parser/printer on given files\n" "$0"
    printf "Usage:\n  %s SEXP-FILE [SEXP-FILE [SEXP-FILE [...]]]\n" "$0"
}

if (( $# < 1 )); then
    printf "Error: Not enough arguments\n"
    usage
fi

for f in "$@"; do
    printf "Testing %s\n" "$f"
    dist/build/sexp/sexp -t "$f" || { printf "Failed on %s\n" "$f"; false; }
done
